/*
 * This source file was generated by the Gradle 'init' task
 */
package com.furnituredesigner;

import com.furnituredesigner.client.ui.LoginPanel;
import com.furnituredesigner.client.ui.MainFrame;
import com.furnituredesigner.client.ui.SuperAdminSetupPanel;
import com.furnituredesigner.common.model.User;
import com.furnituredesigner.server.service.UserService;

import javax.swing.*;
import java.awt.*;
import java.sql.SQLException;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;

public class App {
    private static JFrame loginFrame;
    
    public static void main(String[] args) {
        System.out.println("Starting RoomForge Application...");
        
        // Launch the GUI on the Event Dispatch Thread
        SwingUtilities.invokeLater(() -> {
            try {
                // Set FlatLaf look and feel
                try {
                    FlatMaterialLighterIJTheme.setup();
                } catch (Exception e) {
                    // If the theme couldn't be set up, fall back to the default look and feel
                    FlatLightLaf.setup();
                }
                
                // Show splash screen
                showSplashScreen();
                
            } catch (Exception e) {
                System.err.println("Error starting GUI: " + e.getMessage());
                e.printStackTrace();
                
                // Show error dialog if GUI fails to load
                JOptionPane.showMessageDialog(null, 
                    "Failed to start application: " + e.getMessage(), 
                    "Startup Error", 
                    JOptionPane.ERROR_MESSAGE);
                System.exit(1);
            }
        });
    }
    
    private static void showSplashScreen() {
        // Fully qualified name to avoid ambiguity with java.awt.SplashScreen
        com.furnituredesigner.client.ui.SplashScreen splashScreen = 
            new com.furnituredesigner.client.ui.SplashScreen(new com.furnituredesigner.client.ui.SplashScreen.SplashScreenListener() {
                @Override
                public void onSplashScreenComplete() {
                    checkSuperAdmin();
                }
            });
        
        splashScreen.start();
    }
    
    private static void checkSuperAdmin() {
        try {
            UserService userService = new UserService();
            boolean superAdminExists = userService.isSuperAdminExists();
            
            System.out.println("Checking for SuperAdmin: " + (superAdminExists ? "exists" : "doesn't exist"));
            
            if (superAdminExists) {
                // Super admin exists, show login screen
                showLoginScreen();
            } else {
                // No super admin, show setup screen
                showSuperAdminSetupScreen();
            }
            
        } catch (SQLException e) {
            System.err.println("Database error: " + e.getMessage());
            e.printStackTrace();
            
            JOptionPane.showMessageDialog(null, 
                "Database error: " + e.getMessage(), 
                "Startup Error", 
                JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
    }
    
    private static void showSuperAdminSetupScreen() {
        JFrame setupFrame = new JFrame("RoomForge - Initial Setup");
        setupFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setupFrame.setSize(800, 600);
        setupFrame.setLocationRelativeTo(null);
        
        SuperAdminSetupPanel setupPanel = new SuperAdminSetupPanel(new SuperAdminSetupPanel.SetupListener() {
            @Override
            public void onSetupComplete(User user) {
                // Close setup frame
                setupFrame.dispose();
                
                // Continue to main application
                startMainApplication(user);
            }
        });
        
        setupFrame.add(setupPanel);
        setupFrame.setVisible(true);
        
        System.out.println("SuperAdmin setup screen displayed");
    }
    
    public static void showLoginScreen() {
        if (loginFrame != null && loginFrame.isDisplayable()) {
            loginFrame.setVisible(true);
            loginFrame.toFront();
            return;
        }
        
        loginFrame = new JFrame("RoomForge - Login");
        loginFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        loginFrame.setSize(900, 600);
        loginFrame.setLocationRelativeTo(null);
        
        LoginPanel loginPanel = new LoginPanel(new LoginPanel.LoginListener() {
            @Override
            public void onLoginSuccess(User user) {
                // Close login frame
                loginFrame.dispose();
                
                // Start main application
                startMainApplication(user);
            }
        });
        
        loginFrame.add(loginPanel);
        loginFrame.setVisible(true);
        
        System.out.println("Login screen displayed");
    }
    
    private static void startMainApplication(User user) {
        // Create and show main application frame
        MainFrame mainFrame = new MainFrame(user);
        mainFrame.setVisible(true);
        
        System.out.println("Main application started for user: " + user.getUsername() + " (" + user.getRole() + ")");
    }
}
